sudo: false

language: node_js

node_js:
  - 6

cache:
  directories:
    - node_modules

install:
  - npm install -g npm@latest
  - npm install

script:
  - npm run lint
  - npm run build
  - npm run package
